from Tkinter import *
wndw=Tk()
frame1=Frame(wndw)
frame1.pack()
frame2=Frame(wndw)
frame2.pack(side=BOTTOM)
red=Button(frame1,text="Red",bg="red")
red.pack(side=LEFT)
green=Button(frame1,text="Green",bg="green")
green.pack(side=LEFT)
blue=Button(frame1,text="Blue",bg="blue")
blue.pack(side=LEFT)
black=Button(frame2,text="Black",bg="black")
black.pack(side=BOTTOM)
wndw.mainloop()
